### ISSUE TITLE
command returns newline (doesn't work)

### ISSUE THREAD

**Issue by brianyang** [ruyadorno/ipt#45]
I've tried to simply list the folder and pipe this to ipt, but nothing happens. 

trying this on windows, with the command prompt and with hyper 

![image](https://user-images.githubusercontent.com/81162/38418689-71426580-396b-11e8-9147-035e62b7fb40.png)

```
$ ls | ipt

$ 

$ node -v
v9.8.0
```

how can I debug what's going wrong?

**Comment by ruyadorno** [comment]
which version of windows? can you please also give it a try on powershell? 🤔
