### ISSUE TITLE
Multi Selection Spacing

### ISSUE THREAD

**Issue by sabrehagen** [ruyadorno/ipt#49]
Hi,

Thanks for a great tool. When using the `-m` option the multi-selection character overlaps the option text. However when items are selected the multi-selection character changes and does not overlap the option text.

Could either some spacing be added to prevent this, or a different multi-selection character chosen?

![image](https://user-images.githubusercontent.com/1094600/47550850-341f2b80-d94c-11e8-8f28-d6b70aee39b0.png)

**Comment by ruyadorno** [comment]
hi @sabrehagen, it seems to me to be more of a font issue and probably will depend heavily on the system, if you still would like to have a better looking UI in this case (by now I guess you might as well have gotten used to it 😂 ) I would suggest you to maybe give it a try fixing it in https://github.com/SBoudrias/Inquirer.js which is the UI library that provides all the prompts used in **ipt** 😊 

sorry about the long delay and thanks for the comment, I hope you still enjoy **ipt** 😄
