### ISSUE TITLE
Autocomplete flag regression

### ISSUE THREAD

**Issue by shedali** [ruyadorno/ipt#56]
using `-a` or `--autocomplete` does not work for the following example:

```bash
echo "one, two, three" | ipt --autocomplete -s=,
```

ipt@1.1.0: ✅
ipt@2.1.0: ✅
ipt@2.1.2: ☠️

tested: node 12.3.1, 10.16.0

**Comment by ruyadorno** [comment]
Interesting, I tried it on my local system (with both node@10.16.0 and node@12.7.0) and everything is working as expected, do you get any error message? (you could try adding the `--debug` flag to see if anything pops up in case you get nothing)

**Comment by shedali** [comment]
Thanks for checking. With debug it reported `cannot find module 'rxjs/operators'

https://asciinema.org/a/jbu5zWVyfqd1DaJyZz54QzBKC

I debugged some more and found it only occurs when installed globally with pnpm but works fine with yarn. 

Perhaps related to pnpm instead

**Comment by ruyadorno** [comment]
Yeah, def seems related to the pnpm install. I might leave this open for a while and see if anyone else has the same issue but I'd say for now you're better off using **npm** or **yarn** 😊

**Comment by shedali** [comment]
agree, thanks!

**Comment by ruyadorno** [comment]
should be fixed for pnpm too now that I landed the fix for it in [inquirer-autocomplete-prompt-ipt](https://www.npmjs.com/package/inquirer-autocomplete-prompt-ipt)

**Comment by shedali** [comment]
nice one @ruyadorno
