### ISSUE TITLE
Add ability to filter

### ISSUE THREAD

**Issue by aeciolevy** [ruyadorno/ipt#63]
It would be great to have the ability to filter the results after with list the options.

I can achieve this if a grep before `ipt` but would be awesome to do it after.

![2020-02-14 06 10 43](https://user-images.githubusercontent.com/16165803/74526185-d58b1180-4ef0-11ea-9226-943d3a5bbd97.gif)

**Comment by ruyadorno** [comment]
@aeciolevy this sounds a lot like using the `ipt -a` option instead of the standard interface

is that similar to what you're looking for here?

**Comment by aeciolevy** [comment]
It is... I never tried the fuzzy finder. I will close the issue.
