### ISSUE TITLE
Command returns newline

### ISSUE THREAD

**Issue by rjmunhoz** [ruyadorno/ipt#64]
Hi, I'm using this on macOS and it used to work fine, but has stopped working since my MacBook came back from Apple Support.

Now, whenever I pipe anything to `ipt`, it will do nothing, but print an empty line, like shown in [this capture](https://asciinema.org/a/NLcnkamKvqLPyd4C0BuGq5viY)

As also shown in the asciinema capture, running with `-d` prints `Error: Prompts can not be meaningfully rendered in non-TTY environments` and exits.

Node Version: v13.9.0
macOS Vesrion: 10.15.3 (19D76)
ipt version: 3.0.1

**Comment by ruyadorno** [comment]
Hi @rjmunhoz thanks for the report! Managed to catch it, ended up tracking it to a regression in a patch release of one of the dependencies: https://github.com/SBoudrias/Inquirer.js/pull/891

For now I released a `v3.0.2` in which it fixes the version of that specific dependency to a prior working version, that should fix all problems 😊

**Comment by rjmunhoz** [comment]
Thanks!
